import type { Metadata } from "next";
import { Pirata_One, Funnel_Sans } from "next/font/google";
import "./globals.css";
import RippleGrid from '../components/RippleGrid';
import Navbar from "../components/Navbar";


const pirata = Pirata_One({ 
  variable: "--font-main",
  subsets: ["latin"],
  weight:["400"],
});

const funnel = Funnel_Sans({
  variable: "--font-secondary",
  subsets: ["latin"],
  weight: ["400","800","700","600"],
});

export const metadata: Metadata = {
  title: "Tools overview",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${pirata.variable} ${funnel.variable} antialiased min-h-screen`}
      >
        <Navbar/>
        <div className="absolute inset-0 top-0 z-[-1] min-h-screen">
          <RippleGrid
            enableRainbow={true}  
            gridColor="#ffffff"
            rippleIntensity={0.02}
            gridSize={3}
            gridThickness={20}
            mouseInteraction={true}
            mouseInteractionRadius={1}
            opacity={1}
          />
        </div>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
