import type { Metadata } from "next";
import { Pirata_One, Funnel_Sans } from "next/font/google";
import "./globals.css";
import RippleGrid from './components/RippleGrid';

const pirata = Pirata_One({
  variable: "--font-main",
  subsets: ["latin"],
  weight:["400"],
});

const funnel = Funnel_Sans({
  variable: "--font-secondary",
  subsets: ["latin"],
  weight: ["400","800","700","600"],
});

export const metadata: Metadata = {
  title: "Tools overview",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${pirata.variable} ${funnel.variable} antialiased min-h-screen`}
      >
        {children}
      </body>
    </html>
  );
}
